### ISSUE TITLE
US Cities Example Code

### ISSUE THREAD

**Issue by just-a-beginner** [danthorpe/TaylorSource#33]
Fixed some compile errors by updating the pods in this example code, but when I run the code, I don't seem to have anything in my simulator... 

Am I missing something? Wanted to check out how it works, and was assuming it'd be visible in the simulator

**Comment by danthorpe** [comment]
@just-a-beginner thanks! Are you using Swift 1.2 or Swift 2.0? I take a look into it, as you should definitely see the US States in the simulator.

**Comment by just-a-beginner** [comment]
I am using Swift 2.0. I tried using Edit -> Convert -> To latest Swift Syntax

Didn't make any changes, but it still doesn't open in the simulator. 

Hoping it isn't just me being stupid as that seems to always be the problem >.<

**Comment by danthorpe** [comment]
Okay, there is a `swift_2.0` branch, but I need to update it.

**Comment by danthorpe** [comment]
@just-a-beginner I've just gone through the project and updated all the pods and checked everything is working on both the `development` and `swift_2.0` branches.

I recommend you checkout the repo, switch to `swift_2.0` and then look at the Datasources and US Cities examples. You should be able to run both of these projects in the simulator. The Gallery example doesn't work in Swift 2.0 because one of it's dependencies isn't ready for Swift 2.0 yet.

Also, if you happen to run `pod update` in any of the examples, then you'll need to disable `ENABLE_BITCODE` in the build settings for each of the projects - e.g. app & Pods. I think this is a current issue in CocoaPods / Xcode 7. YapDatabase weak links against sqlite3 and this is not compatible with Bitcode, which is now on by default.

I'm going to close this particular issue, however if you have any more questions about TaylorSource, YapDatabaseExtensions, or even YapDatabase, feel free to create a new issue in either this repo or [YapDatabaseExtensions](http://github.com/danthorpe/yapdatabaseextensions).
